const KEY='walklibrary-v02';
const seed=[{id:'castle-tioram',name:'Castle Tioram',area:'Loch Moidart, Scottish Highlands',status:'planned',distance:null,ascent:null,duration:'',lat:56.7836,lng:-5.8287,tags:['wild','coastal','castle'],notes:'March 2027 idea. Visit Eilean Tioram around a safe tidal crossing window. Camp on suitable mainland ground rather than the Scheduled Monument. Check weather and tides before travelling.',gpx:null,created:'2026-09-29'}];
let walks=load();let currentFilter='all',editingId=null,map=null,layers=[];
function load(){try{const x=JSON.parse(localStorage.getItem(KEY));return Array.isArray(x)&&x.length?x:seed}catch{return seed}}
function save(){localStorage.setItem(KEY,JSON.stringify(walks));renderAll()}
const $=id=>document.getElementById(id);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function statusLabel(s){return s==='planned'?'Planned':s==='completed'?'Completed':'Saved'}
function renderAll(){renderList();renderTrips();if(map)renderMap()}
function filtered(){const q=$('search').value.trim().toLowerCase();return walks.filter(w=>{const f=currentFilter==='all'||(currentFilter==='completed'&&w.status==='completed')||w.tags.includes(currentFilter);const t=(w.name+' '+w.area+' '+w.tags.join(' ')).toLowerCase().includes(q);return f&&t})}
function renderList(){const list=$('walkList'),arr=filtered();list.innerHTML=arr.length?arr.map(w=>`<article class="card"><div class="cardTop"><div><div class="eyebrow">${esc(w.area||'SAVED WALK')}</div><h3>${esc(w.name)}</h3></div><span class="badge">${statusLabel(w.status)}</span></div><div class="meta">${w.distance?`<span>🥾 ${w.distance} km</span>`:''}${w.ascent?`<span>↗ ${w.ascent} m</span>`:''}${w.duration?`<span>◷ ${esc(w.duration)}</span>`:''}${w.gpx?`<span>✓ GPX saved</span>`:''}</div><div class="tags">${w.tags.map(t=>`<span class="tag">${esc(t)}</span>`).join('')}</div><div class="cardActions"><button data-detail="${w.id}">Details</button><button class="primary" data-map="${w.id}">View map</button></div></article>`).join(''):'<div class="empty">No walks match this filter.</div>'}
function renderTrips(){const arr=walks.filter(w=>w.status==='planned');$('tripList').innerHTML=arr.length?arr.map(w=>`<article class="card"><div class="eyebrow">PLANNED TRIP</div><h3>${esc(w.name)}</h3><div class="area">${esc(w.area)}</div><p class="note">${esc(w.notes||'No trip notes yet.')}</p><div class="cardActions"><button data-detail="${w.id}">Open</button><button class="primary" data-map="${w.id}">Map</button></div></article>`).join(''):'<div class="empty">No planned trips yet. Edit a saved walk and set its status to Planned trip.</div>'}
function setView(id){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id));document.querySelectorAll('.nav').forEach(b=>b.classList.toggle('active',b.dataset.view===id));if(id==='mapView'){initMap();setTimeout(()=>map&&map.invalidateSize(),80)}}
function initMap(){if(map||!window.L)return;map=L.map('map').setView([56.6,-4.5],6);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap contributors'}).addTo(map);renderMap()}
function renderMap(focusId){if(!map)return;layers.forEach(l=>map.removeLayer(l));layers=[];const bounds=[];walks.forEach(w=>{let pts=w.gpx?.points||[];if(pts.length){const line=L.polyline(pts.map(p=>[p.lat,p.lng]),{weight:5}).addTo(map);line.bindPopup(`<h3>${esc(w.name)}</h3>${esc(w.area)}`);layers.push(line);pts.forEach(p=>bounds.push([p.lat,p.lng]));}const lat=Number(w.lat),lng=Number(w.lng);if(Number.isFinite(lat)&&Number.isFinite(lng)){const m=L.marker([lat,lng]).addTo(map).bindPopup(`<h3>${esc(w.name)}</h3>${esc(w.area)}<br>${statusLabel(w.status)}`);layers.push(m);bounds.push([lat,lng]);if(focusId===w.id){map.setView([lat,lng],13);m.openPopup()}}});if(!focusId&&bounds.length)map.fitBounds(bounds,{padding:[30,30],maxZoom:12})}
function showDetail(id){const w=walks.find(x=>x.id===id);if(!w)return;editingId=id;$('detailStatus').textContent=statusLabel(w.status).toUpperCase();$('detailName').textContent=w.name;$('detailBody').innerHTML=`<div class="area">${esc(w.area)}</div><div class="detailGrid"><div class="stat"><strong>${w.distance??'—'}</strong><small>KM</small></div><div class="stat"><strong>${w.ascent??'—'}</strong><small>ASCENT M</small></div><div class="stat"><strong>${esc(w.duration||'—')}</strong><small>DURATION</small></div></div><div class="tags">${w.tags.map(t=>`<span class="tag">${esc(t)}</span>`).join('')}</div><p>${esc(w.notes||'No notes yet.')}</p><p class="note">${w.gpx?`GPX stored offline • ${w.gpx.points.length} track points`:'No GPX route imported yet.'}</p>`;$('detailDialog').showModal()}
function openForm(id){editingId=id||null;const w=id?walks.find(x=>x.id===id):null;$('formMode').textContent=w?'EDIT SAVED WALK':'NEW SAVED WALK';$('formTitle').textContent=w?w.name:'Add walk';$('walkId').value=w?.id||'';$('name').value=w?.name||'';$('area').value=w?.area||'';$('status').value=w?.status||'saved';$('distance').value=w?.distance??'';$('ascent').value=w?.ascent??'';$('duration').value=w?.duration||'';$('lat').value=w?.lat??'';$('lng').value=w?.lng??'';$('tags').value=w?.tags?.join(', ')||'';$('notes').value=w?.notes||'';$('gpx').value='';$('gpx').dataset.parsed='';$('gpxState').textContent=w?.gpx?`Existing GPX: ${w.gpx.points.length} track points`:'No GPX selected';$('deleteBtn').classList.toggle('hidden',!w);$('walkDialog').showModal()}
function parseGpx(text){const xml=new DOMParser().parseFromString(text,'application/xml');if(xml.querySelector('parsererror'))throw new Error('Invalid GPX file');const nodes=[...xml.querySelectorAll('trkpt,rtept')];const points=nodes.map(n=>({lat:Number(n.getAttribute('lat')),lng:Number(n.getAttribute('lon'))})).filter(p=>Number.isFinite(p.lat)&&Number.isFinite(p.lng));if(points.length<2)throw new Error('No usable track points found');return {points};}
$('gpx').addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;try{const g=parseGpx(await f.text());e.target.dataset.parsed=JSON.stringify(g);$('gpxState').textContent=`Ready: ${g.points.length} track points`;if(!$('lat').value){$('lat').value=g.points[0].lat;$('lng').value=g.points[0].lng}}catch(err){e.target.value='';$('gpxState').textContent=err.message}});
$('walkForm').addEventListener('submit',e=>{e.preventDefault();const old=editingId?walks.find(x=>x.id===editingId):null;let gpx=old?.gpx||null;if($('gpx').dataset.parsed)gpx=JSON.parse($('gpx').dataset.parsed);const w={id:old?.id||('walk-'+Date.now()),name:$('name').value.trim(),area:$('area').value.trim(),status:$('status').value,distance:$('distance').value?Number($('distance').value):null,ascent:$('ascent').value?Number($('ascent').value):null,duration:$('duration').value.trim(),lat:$('lat').value?Number($('lat').value):null,lng:$('lng').value?Number($('lng').value):null,tags:$('tags').value.split(',').map(x=>x.trim().toLowerCase()).filter(Boolean),notes:$('notes').value.trim(),gpx,created:old?.created||new Date().toISOString().slice(0,10)};if(!w.name)return;if(old)walks=walks.map(x=>x.id===w.id?w:x);else walks.unshift(w);save();$('walkDialog').close()});
$('deleteBtn').onclick=()=>{if(editingId&&confirm('Delete this saved walk?')){walks=walks.filter(x=>x.id!==editingId);save();$('walkDialog').close()}};
$('addBtn').onclick=()=>openForm();$('closeDialog').onclick=$('cancelBtn').onclick=()=>$('walkDialog').close();$('closeDetail').onclick=()=>$('detailDialog').close();$('editBtn').onclick=()=>{$('detailDialog').close();openForm(editingId)};$('detailMap').onclick=()=>{$('detailDialog').close();setView('mapView');setTimeout(()=>renderMap(editingId),120)};
document.addEventListener('click',e=>{const d=e.target.closest('[data-detail]'),m=e.target.closest('[data-map]');if(d)showDetail(d.dataset.detail);if(m){setView('mapView');setTimeout(()=>renderMap(m.dataset.map),120)}});
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>setView(b.dataset.view));document.querySelectorAll('.chip').forEach(b=>b.onclick=()=>{document.querySelectorAll('.chip').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');currentFilter=b.dataset.filter;renderList()});$('search').oninput=renderList;$('fitBtn').onclick=()=>renderMap();
function network(){const on=navigator.onLine;document.body.classList.toggle('online',on);document.body.classList.toggle('offline',!on);$('netText').textContent=on?'Online':'Offline';$('offlineMap').classList.toggle('hidden',on);$('map').classList.toggle('hidden',!on);if(on&&document.querySelector('#mapView.active')){initMap();setTimeout(()=>map&&map.invalidateSize(),100)}}window.addEventListener('online',network);window.addEventListener('offline',network);network();renderAll();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');
